### ISSUE TITLE
unable to start

### ISSUE THREAD

**Issue by pradeepbossngn** [wr3cckl3ss/-system3#7]
hi good afternoon bro

this mail regarding for Trading-View-crack-v4.1.2. when i try to open bot-manager it's show's an error. i am submitting the screenshot
![error](https://github.com/wr3cckl3ss/-Trading-view-crack-2024/assets/157202458/2dbba67c-8544-4969-8fc7-b7d38815fe0c)

**Comment by bitten2up** [comment]
looks like `Client-update_Data` is using unity????


![image](https://github.com/wr3cckl3ss/system3/assets/55027142/7b64263a-0721-44e0-8b27-7624b0b2fcbc)

**Comment by bitten2up** [comment]
assume this is malware for now, they put this on a completely unrelated GitHub repo from what I can tell

**Comment by bitten2up** [comment]
OH CRYPTO SCAM, yeah um probably malware
